globals:
- id: unmasked_value_register_0
  initial_value: '0'
  restore_value: false
  type: uint16_t
- id: unmasked_value_register_5
  initial_value: '0'
  restore_value: false
  type: uint16_t
- id: unmasked_value_water_temperature_t1s
  initial_value: '0'
  restore_value: false
  type: uint16_t
- id: unmasked_curve_selection
  initial_value: '0'
  restore_value: false
  type: uint16_t
- id: unmasked_value_register_210
  initial_value: '0'
  restore_value: false
  type: uint16_t
- id: unmasked_value_register_211
  initial_value: '0'
  restore_value: false
  type: uint16_t
- id: unmasked_value_register_270
  initial_value: '0'
  restore_value: false
  type: uint16_t
- id: unmasked_value_register_272
  initial_value: '0'
  restore_value: false
  type: uint16_t
substitutions:
  description: Heatpump Controller
  devicename: heatpump
esp32:
  board: esp32dev
  framework:
    type: esp-idf
esphome:
  comment: ${description}
  friendly_name: ${description}
  name: ${devicename}
  project:
    name: ${devicename}.${description}
    version: 1.0.0e
