name: Update Heatpump Version

on:
  release:
    types: [published]

jobs:
  update_version:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub Actions token
      REPO_OWNER: ${{ github.repository_owner }}   # Repository owner
      DEFAULT_NAME: "rysiulg"                 # Fallback name
      DEFAULT_EMAIL: "rysiulg@gmail.com"         # Fallback email
      TARGET_BRANCH: "master"                       # Target branch name

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: |
          pip install pyyaml

      - name: Get Repository Owner Details
        id: repo_details
        run: |
          TOKEN="${GITHUB_TOKEN}"
          OWNER="${REPO_OWNER}"
          RESPONSE=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/users/$OWNER")
          
          echo "API Response: $RESPONSE"  # Debugging line
          
          NAME=$(echo "$RESPONSE" | jq -r '.name')
          EMAIL=$(echo "$RESPONSE" | jq -r '.email')

          # Fallback to default values if NAME or EMAIL is empty
          if [ -z "$NAME" ]; then
            NAME="${{ env.DEFAULT_NAME }}"
          fi
          if [ -z "$EMAIL" ]; then
            EMAIL="${{ env.DEFAULT_EMAIL }}"
          fi

          echo "name=$NAME" >> $GITHUB_ENV
          echo "email=$EMAIL" >> $GITHUB_ENV

      - name: Update Version
        run: python update_version.py ${{ github.event.release.tag_name }}

      - name: Commit Changes
        run: |
          git config --local user.email "$EMAIL"
          git config --local user.name "$NAME"
          git add heatpump.yaml CHANGELOG.md
          git commit -m "Update version to ${{ github.event.release.tag_name }}"
          git push origin HEAD:${{ env.TARGET_BRANCH }}  # Use the variable for the target branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
