name: Update Heatpump Version

on:
  release:
    types: [published]

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: |
          pip install pyyaml

      - name: Update Version
        run: python update_version.py ${{ github.event.release.tag_name }}

      - name: Commit Changes
        run: |
          git config --local user.email "rysiulg@gmail.com"
          git config --local user.name "rysiulg"
          git add heatpump.yaml CHANGELOG.md
          git commit -m "Update version to ${{ github.event.release.tag_name }}"
          git push origin HEAD:master  # Change "main" if your default branch is different
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
