name: Update Heatpump Version

on:
  release:
    types: [published]

jobs:
  update_version:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub Actions token
      DEFAULT_NAME: "github-actions[bot]"
      DEFAULT_EMAIL: "github-actions[bot]@users.noreply.github.com"
      TARGET_BRANCH: "master"                       # Target branch name

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Python
        uses: actions/setup-python@v4  # Confirm that this is the latest version
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: |
          pip install pyyaml

      - name: Set Git Config
        run: |
          echo "Using NAME: ${{ env.DEFAULT_NAME }}"
          echo "Using EMAIL: ${{ env.DEFAULT_EMAIL }}"
          git config --local user.email "${{ env.DEFAULT_EMAIL }}"
          git config --local user.name "${{ env.DEFAULT_NAME }}"

      - name: Update Version
        run: python update_version.py ${{ github.event.release.tag_name }}

      - name: Commit Changes
        run: |
          git add heatpump.yaml CHANGELOG.md
          git commit -m "Update version to ${{ github.event.release.tag_name }}"
          git push origin HEAD:${{ env.TARGET_BRANCH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
